name: WINDOWS 2019 RDP

on:
  workflow_dispatch

jobs:
  build:
    runs-on: windows-2019
    timeout-minutes: 9999

    steps:
      - name: Download Ngrok and other scripts
        run: |
          Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/start.bat -OutFile start.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Riders004/rdp/master/download1.jpeg -OutFile wallpaper.bat
          Invoke-WebRequest https://raw.githubusercontent.com/Vip3rLi0n/Ngrok-RDPs/main/resources/loop.ps1 -OutFile loop.ps1

      - name: Extract Ngrok
        run: Expand-Archive ngrok.zip

      - name: Apply Ngrok Authtoken
        run: |
          ./ngrok/ngrok.exe authtoken 1stumZJSpHTjdZ0X7JPszAdcUL8_53XN4igGwTPX3VBdndGna
          Write-Output "Ngrok authtoken has been applied successfully."

      - name: Configure Windows RDP
        run: |
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -Name "fDenyTSConnections" -Value 0
          Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
          Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -Name "UserAuthentication" -Value 1
          Copy-Item -Path wallpaper.bat -Destination D:\a\wallpaper.bat

      - name: Start Ngrok Tunnel
        run: Start-Process PowerShell -ArgumentList '-NoExit -Command "./ngrok/ngrok.exe tcp --region ap 3389"'

      - name: Start RDP Setup
        run: cmd /c start.bat

      - name: Keep Session Alive
        run: ./loop.ps1
